1. Bag of Words

In [1]:
import pandas as pd

feature_vectors = []

word_text = ["The is a very very cute cat", "The dog is very cute"]

tokens = [token.split() for token in word_text]
vocab  = list(set([word for text in tokens for word in text]))

for text in tokens:
    feature_vector = [0]*len(vocab)
    for word in text:
        feature_vector[vocab.index(word)] = text.count(word)        
    feature_vectors.append(feature_vector)

df = pd.DataFrame(feature_vectors, columns = vocab)
df['word_corpus'] = word_text
df

   a  dog  cute  is  cat  very  The                  word_corpus
0  1    0     1   1    1     2    1  The is a very very cute cat
1  0    1     1   1    0     1    1         The dog is very cute

2. Binary Bag of Words

In [2]:
import pandas as pd

feature_vectors = []

word_text = ["The is a very very cute cat", "The dog is very cute"]

tokens = [token.split() for token in word_text]
vocab  = list(set([word for text in tokens for word in text]))

for text in tokens:
    feature_vector = [0]*len(vocab)
    for word in text:
        if word in vocab:
            feature_vector[vocab.index(word)] = 1
    feature_vectors.append(feature_vector)

df = pd.DataFrame(feature_vectors, columns = vocab)
df['word_corpus'] = word_text
df

   a  dog  cute  is  cat  very  The                  word_corpus
0  1    0     1   1    1     1    1  The is a very very cute cat
1  0    1     1   1    0     1    1         The dog is very cute